#!/usr/bin/env bash
# Opens the watchdog's issue, or comments on the one it already opened.
# Reads findings.md from the working directory.
#
# Environment: GH_TOKEN, REPO, MARKER.
# Covered by test/workflows/watchdog.test.sh — run it after editing.
set -eo pipefail

# shellcheck source=lib/gh-api.sh
. "$(dirname "$0")/lib/gh-api.sh"

title="chore: a release is waiting"

{
  echo "$MARKER"
  echo "The release watchdog found something waiting:"
  echo
  cat findings.md
  echo
  echo "Raised by [\`release-watchdog.yml\`](https://github.com/$REPO/blob/main/.github/workflows/release-watchdog.yml). Close this issue once the release is out — a new one is opened if the situation comes back."
  echo
  echo "---"
  echo "_Generated by [Claude Code](https://claude.ai/code)_"
} > body.md

# Deliberately not `|| true`: if this lookup fails we do not know whether an
# issue already exists, and guessing means opening a second public issue about
# the same release. Failing is the cheaper mistake — the findings are in the log
# and tomorrow's run retries.
if ! issues=$(api --paginate "repos/$REPO/issues?state=open&per_page=100"); then
  echo "::error::could not list open issues; refusing to risk a duplicate report"
  exit 1
fi

# Restricted to issues this workflow authored, with the marker leading the body.
# Anyone can open an issue in a public repository and an HTML comment is
# invisible once rendered — without the author filter a stranger could quietly
# capture every future report. `last` on a created-desc list is the oldest match,
# so a newer issue cannot supersede the one already being updated.
existing=$(jq -rs --arg t "$title" --arg m "$MARKER" 'add // []
  | map(select(.pull_request == null))
  | map(select((.user.login // "") == "github-actions[bot]"))
  | map(select(.title == $t or ((.body // "") | startswith($m))))
  | last // empty' <<<"$issues")

if [ -n "$existing" ]; then
  number=$(jq -r '.number' <<<"$existing")
  echo "updating existing issue #$number"
  gh api "repos/$REPO/issues/$number/comments" -F body=@body.md >/dev/null
else
  echo "opening a new issue"
  gh api "repos/$REPO/issues" -f title="$title" -F body=@body.md >/dev/null
fi
