packages:
  - ./
  - cli
  - docs
  - playgrounds/nuxt
  - playgrounds/vue
  - playgrounds/repl
  - playgrounds/demo

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

overrides:
  '@nuxt/kit': ^4.4.6
  '@bitrix24/b24ui-nuxt': workspace:*
  nitropack: ^2.13.0
  unplugin: ^3.0.0
  c12: ^3.3.2
  h3: 1.15.11
  unimport: 6.0.2

allowBuilds:
  better-sqlite3: true
  puppeteer: true
  sharp: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  '@vercel/speed-insights': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
